---
- name: restart sshd
  become: true
  service: name=sshd state=restarted

- name: restart systemd-networkd
  become: true
  service: name=systemd-networkd state=restarted

- name: restart dnsmasq
  become: true
  service: name=dnsmasq state=restarted

- name: load nf_conntrack
  become: true
  modprobe:
    name: nf_conntrack
    state: present
