---
- name: restart ssh
  become: true
  service: name=ssh state=restarted

- name: restart systemd-networkd
  become: true
  service: name=systemd-networkd state=restarted

- name: load nf_conntrack
  become: true
  modprobe:
    name: nf_conntrack
    state: present
